// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Adicionado para depuração: verificar se as variáveis de ambiente estão sendo carregadas e seu comprimento
console.log("Supabase Client Init: URL Length:", SUPABASE_URL?.length || 0, "Key Length:", SUPABASE_PUBLISHABLE_KEY?.length || 0);
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Supabase environment variables are missing! Please check your .env file.");
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public', // Força o cliente a usar o esquema 'public' e a recarregar seu cache.
  },
  global: {
    timeout: 30000, // 30 segundos
  }
});

// Teste de conectividade inicial
(async () => {
  try {
    // Tentativa de obter o usuário para verificar a conectividade com o serviço de autenticação
    const { data, error } = await supabase.auth.getUser();
    if (error) {
      console.error("Supabase Client Init: Initial auth connection test failed:", error.message);
    } else {
      console.log("Supabase Client Init: Initial auth connection test successful.");
    }
  } catch (e: any) {
    console.error("Supabase Client Init: Unexpected error during initial auth connection test:", e.message);
  }
})();

// A linha abaixo foi removida pois supabase.realtime.on não é uma função válida.
// O monitoramento de conexão geral já é feito no Navbar.tsx.
// supabase.realtime.on('error', (err) => {
//   console.error('[Supabase Realtime Error]', err);
// });