// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Certifique-se de que estas variáveis estão sendo lidas corretamente
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Adicionado para depuração: verificar se as variáveis de ambiente estão sendo carregadas
console.log("Supabase Client Init: URL:", SUPABASE_URL ? "Loaded" : "NOT LOADED", "Key:", SUPABASE_PUBLISHABLE_KEY ? "Loaded" : "NOT LOADED");
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Supabase environment variables are missing! Please check your .env file.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public', // Força o cliente a usar o esquema 'public' e a recarregar seu cache.
  }
});

// Adicionado para forçar a atualização do cache do esquema do cliente Supabase.